# Generated by Django 4.0.1 on 2022-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True),
        ),
    ]
